/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./src/components/ParticleScene/1.vue')['default']
    2: typeof import('./src/components/ParticleScene/ParticleScene copy 2.vue')['default']
    4: typeof import('./src/components/ParticleScene/4.vue')['default']
    copy: typeof import('./src/components/ParticleScene/ParticleScene copy.vue')['default']
    KidCom: typeof import('./src/components/kid-com.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NLi: typeof import('naive-ui')['NLi']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NOl: typeof import('naive-ui')['NOl']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    ParticleScene: typeof import('./src/components/ParticleScene/ParticleScene.vue')['default']
    ParticleScene1: typeof import('./src/components/ParticleScene/ParticleScene1.vue')['default']
    ParticleScene2: typeof import('./src/components/ParticleScene/ParticleScene2.vue')['default']
    ParticleScene3: typeof import('./src/components/ParticleScene/ParticleScene3.vue')['default']
    ParticleScene4: typeof import('./src/components/ParticleScene/ParticleScene4.vue')['default']
    ParticleScene5: typeof import('./src/components/ParticleScene/ParticleScene5.vue')['default']
    PubgSupportFooter: typeof import('./src/components/pubgSupportFooter.vue')['default']
    PubgSupportHeader: typeof import('./src/components/pubgSupportHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VillageScene: typeof import('./src/components/VillageScene/VillageScene.vue')['default']
  }
}
